<br>
<h2>Форма додавання нового проєкту</h2><br>
<form method="POST">
    <label>
        Код
        <input type="number" id="code" name="code" placeholder="Code (Example: 6)">
    </label><br>
    <label>
        ПІБ автора
        <input type="text" id="author" name="author" placeholder="Author (Example: Вогар Андрій)">
    </label><br>
    <label>
        Кошторис
        <input type="number" id="estimate" name="estimate" placeholder="Estimate (Example: 20000)">
    </label><br>
    <label>
        Перша оцінка
        <input type="number" id="score1" name="score1">
    </label><br>
    <label>
        Друга оцінка
        <input type="number" id="score2" name="score2">
    </label><br>
    <label>
        Третя оцінка
        <input type="number" id="score3" name="score3" >
    </label><br>
    <button type="submit">Add</button>
</form>