<br>
<h2>Форма додавання нового проєкту</h2>
<form method="POST">
    <label>
        <input type="number" id="code" name="code" placeholder="Code (Example: 6)">
    </label>
    <label>
        <input type="text" id="author" name="author" placeholder="Author (Example: Вогар Андрій)">
    </label>
    <label>
        <input type="number" id="estimate" name="estimate" placeholder="Estimate (Example: 20000)">
    </label>
    <button type="submit">Add</button>
</form>