<?php
/** @var array $projects */
$projects;
?>

<hr>
<center>
<h2>Таблиця проєктів</h2>
<table border="1">
    <tr>
        <th>Код</th>
        <th>Автор</th>
        <th>Кошторис</th>
        <th>Оцінки</th>
    </tr>
    <?php foreach ($projects as $project): ?>
    <tr>
        <td><?= $project['code']; ?></td>
        <td><?= $project['author']; ?></td>
        <td><?= $project['estimate']; ?></td>
        <td><?= implode(',',$project['scores']); ?></td>
    </tr>
    <?php endforeach;?>
</table>
</center>
